server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-user-service
          uri: lb://auth-user-service
          predicates:
            - Path=/api/auth/**, /api/users/**
        - id: ticket-service
          uri: lb://ticket-service
          predicates:
            - Path=/api/tickets/**
          filters:
            - JwtValidationFilter
        - id: assignment-service
          uri: lb://assignment-service
          predicates:
            - Path=/api/assignments/**
          filters:
            - JwtValidationFilter
        - id: notification-analytics-service
          uri: lb://notification-analytics-service
          predicates:
            - Path=/api/notifications/**, /api/analytics/**
          filters:
            - JwtValidationFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: ${JWT_SECRET}
